
name: bwa_flutix
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.8.1
  cloud_firestore: ^4.8.0
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  provider: ^6.1.2
  google_fonts: ^5.0.0
  email_validator: ^2.0.1
  another_flushbar: ^1.12.0
  flutter_spinkit: ^5.2.0
  material_design_icons_flutter: ^6.0.0
  intl: ^0.18.0
  image_picker: ^0.8.7+5
  http: ^1.1.0
  random_string: ^2.3.1
  qr_flutter: ^4.0.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
